# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://bybunni.github.io/raytracing/"

git_url = "https://github.com/bybunni/raytracing/tree/master/"

def custom_doc_links(name): return None
